### PR TITLE
Little changes.(Did you forget this repository?)

### PR DESCRIPTION
**Pull request by libertas**
First:Makefile added.

Second:New method "Append" added.

There were only some little changes,but I am interested in this repository.I will make some other changes,wait me please!

### CODE REVIEW

**Comment by toddhainsworth** [comment]
I barely use this repository any more, also a note, you are violating the terms of the GPL by not including credit to the original author(s) who is/are mentioned in my comments on the source.

I will not pull these changes until appropriate changes to your project are made.
- Change text and license to original that is included with my source
- Make sure that the code you push to this repo does not delete original branding.

NOTE: I am not the original author of this software, it is only here as a hobby.

**Comment by libertas** [comment]
I'm sorry for my behaviour.
But I think a free software is good for anyone.
Would you please ask the original author if he will use some free
license(GPL,LGPL,BSD or others)?Thanks you very much.
One of my friends saw my fork of the repository,and he borrowed some
concept,reworte the software.His software is a free software under GPLv2.So
if I don't have right to modify your software,I will turn to him.
Thanks for your responsibility.

2012/8/3 GeissT <
reply@reply.github.com

**Comment by toddhainsworth** [comment]
Please read the licensing of my original source. You will see that the owner is obviously not really available for contact, they are authors of a book so they most likely do not accept requests.

The license I use is the GPL, therefore you are required to quote me in your project aswell as the original authors (again, located in my source).
Again, if you forfeit my fork of the repository and use your friends, you are still in violation of the GPL if you do not credit him/her.
Thanks.

**Comment by toddhainsworth** [comment]
You will still have access to my repository as long as you make the appropriate changes, listed above.

I am more than happy to help with this process, if you need.

**Pull request closed without merging**
